### ISSUE TITLE
Epoch changes coming soon

### ISSUE THREAD

**Issue by rsandor** [dainbrump/ng-epoch#6]
Hi @dainbrump,

My name is Ryan, and I maintain Epoch. Recently got control of the repository again, and just wanted to let you know that there will be some changes coming pretty soon. What you have here should work with `v0.6.0` and `v0.7.0`. Keep an eye on the the [epoch](https://github.com/epochjs/epoch) repository for any breaking changes.

Cheers

**Comment by dainbrump** [comment]
Thanks for the heads up. The original work was done a while back and my Angular-fu has gotten much better, so I'm planning a rewrite of these directives. I'll keep tabs on the repo.
