### ISSUE TITLE
Cannot be invoked in strict mode

### ISSUE THREAD

**Issue by zapperzme** [dainbrump/ng-epoch#7]
Hi, great job with the project so far guys!

Had an issue as I'm running my app in strict mode:
"epochController is not using explicit annotation and cannot be invoked in strict mode"

Quick fix :
ngEpoch.controller('epochController', ['$scope', '$compile', function ($scope, $compile) { ...code... }]);

Maybe useful for others as well.

Cheers.

**Comment by dainbrump** [comment]
I have a major refactor coming up which should resolve this and other issues. Thanks for the heads up.

**Comment by dainbrump** [comment]
Just did a major update to the library. It's now using the component structure for Angular 1.5. The changes should also fix the annotation issues. Please let me know if there is anything else I can do.
