### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by BenMcLeanHRBlock** [dainbrump/ng-epoch#8]
To use this in some professional settings, it will need to be released under a license that is not only, "OK to use" for now, but which also promises that you won't sue companies for infringing your rights in the future.

Angular.js is released under the MIT license.
Epoch.js is released under the MIT license.

https://opensource.org/licenses/MIT

All you would need to do would be to upload an identical LICENSE file to those used by one of those projects (containing the text of the MIT license) to make this legally safe to use under the same rules as those two underlying frameworks. Can you do that please? It would help me out. Thanks.

**Comment by dainbrump** [comment]
Sorry about getting back so late. I'll update the license shortly. I am planning to pick this project back up real soon.

**Comment by dainbrump** [comment]
License has been updated as well as the library. Please let me know if there is anything else I can help with.

**Comment by BenMcLeanHRBlock** [comment]
Thanks!
